In [9]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import os

In [10]:
df = pd.read_csv("../data/processed/processed_customer_data.csv")

df.head()

,Age,Gender,Education Level,Geographic Information,Occupation,Income Level,Interactions with Customer Service,Insurance Products Owned,Preferred Contact Time,Preferred Language,Segmentation Group
0,-1.401980,-1.028344,-1.365141,0.547943,-0.420389,-0.333617,1.449844,-0.552061,-1.621059,-1.419718,1.270568
1,-1.203033,0.972437,0.057168,-0.637324,0.351183,-0.780348,-1.293483,-1.241050,0.484279,-0.647116,1.270568
2,-1.004085,-1.028344,-1.365141,1.041804,-0.420389,-0.241996,-0.607651,0.136927,-0.217500,0.125487,-0.120496
3,-1.600928,0.972437,-0.653987,1.140576,-0.420389,-0.528975,-1.293483,-0.552061,-0.919279,-0.647116,-0.120496
4,-1.269349,-1.028344,-0.653987,1.733210,0.351183,-1.199821,-1.293483,0.825916,1.186059,-1.419718,-0.816028

In [11]:
X = df.copy()

In [12]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled[:5]

array([[-1.40198032, -1.02834389, -1.36514142,  0.54794282, -0.4203895 ,
        -0.33361745,  1.44984416, -0.55206138, -1.62105876, -1.41971845,
         1.2705678 ],
       [-1.20303269,  0.97243734,  0.05716833, -0.63732391,  0.35118263,
        -0.78034795, -1.29348327, -1.24104994,  0.4842793 , -0.64711586,
         1.2705678 ],
       [-1.00408506, -1.02834389, -1.36514142,  1.04180396, -0.4203895 ,
        -0.24199582, -0.60765141,  0.13692719, -0.21750005,  0.12548673,
        -0.12049575],
       [-1.60092795,  0.97243734, -0.65398654,  1.14057618, -0.4203895 ,
        -0.52897507, -1.29348327, -0.55206138, -0.91927941, -0.64711586,
        -0.12049575],
       [-1.26934857, -1.02834389, -0.65398654,  1.73320955,  0.35118263,
        -1.19982114, -1.29348327,  0.82591575,  1.18605866, -1.41971845,
        -0.81602752]])

In [13]:
os.makedirs("../results/pca_outputs", exist_ok=True)

In [14]:
np.save("../results/pca_outputs/scaled_data.npy", X_scaled)

print("Scaled data saved successfully")

Scaled data saved successfully

In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import os

# load processed data
df = pd.read_csv("../data/processed/processed_customer_data.csv")

# scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

# PCA (2 components for visualization)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

# save scaled data and PCA
os.makedirs("../results/pca_outputs", exist_ok=True)
np.save("../results/pca_outputs/scaled_data.npy", X_scaled)
np.save("../results/pca_outputs/pca_data.npy", X_pca)

In [16]:
import pandas as pd

# Load processed data
df = pd.read_csv("../data/processed/processed_customer_data.csv")

# Feature Engineering

df['Engagement Score'] = df['Interactions with Customer Service'] * df['Insurance Products Owned']

df['Income per Product'] = df['Income Level'] / (df['Insurance Products Owned'] + 1)

df['Age Group'] = pd.cut(df['Age'], bins=3, labels=[0,1,2])

df['High Value'] = (df['Income Level'] > df['Income Level'].mean()).astype(int)

# Save updated dataset
df.to_csv("../data/processed/featured_customer_data.csv", index=False)

df.head()

,Age,Gender,Education Level,Geographic Information,Occupation,Income Level,Interactions with Customer Service,Insurance Products Owned,Preferred Contact Time,Preferred Language,Segmentation Group,Engagement Score,Income per Product,Age Group,High Value
0,-1.401980,-1.028344,-1.365141,0.547943,-0.420389,-0.333617,1.449844,-0.552061,-1.621059,-1.419718,1.270568,-0.800403,-0.744784,0,0
1,-1.203033,0.972437,0.057168,-0.637324,0.351183,-0.780348,-1.293483,-1.241050,0.484279,-0.647116,1.270568,1.605277,3.237287,0,0
2,-1.004085,-1.028344,-1.365141,1.041804,-0.420389,-0.241996,-0.607651,0.136927,-0.217500,0.125487,-0.120496,-0.083204,-0.212851,0,0
3,-1.600928,0.972437,-0.653987,1.140576,-0.420389,-0.528975,-1.293483,-0.552061,-0.919279,-0.647116,-0.120496,0.714082,-1.180910,0,0
4,-1.269349,-1.028344,-0.653987,1.733210,0.351183,-1.199821,-1.293483,0.825916,1.186059,-1.419718,-0.816028,-1.068308,-0.657107,0,0

In [ ]:
#FEATURE ENGINEERING:

- Created Engagement Score to measure customer interaction level.
- Created Income per Product to evaluate spending efficiency.
- Categorized Age into groups for segmentation.
- Identified high-value customers based on income.

These features help improve clustering performance and business understanding.